In [1]:
# practice 2.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
11      1   1   1   0   0   1   1   1   0   1  ...    0    1    0    0    1   
55      0   0   1   0   0   0   1   0   0   0  ...    0    0    0    0    0   
75      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   
69      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
39      1   1   0   1   1   0   0   0   1   1  ...    1    1    1    1    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
57      0   1   1   1   0   1   0   1   1   1  ...    0    1    0    1    0   
76      0   1   0   0   0   1   1   0   0   1  ...    0    1    0    0    0   
71      0   0   0   0   0   0   1   0   0   0  ...    0    0    0    0    0   
20      1   0   0   0   0   0   0   1   0   0  ...    1    0    0    0    0   
60      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   

    F18  F19  F20  F21  F22  
11    0    1    1    0    0  
55    0    0    0    0    0  
75    0    0    0    0    0  
69    0    0    0    0    0  
39    0    1    1    0    0  
..  ...  ...  ...  ...  ...  
57    0    1    0    1    0  
76    0    1    1    0    0  
71    0    0    0    0    0  
20    0    0    0    1    1  
60    0    0    0    0    0  

[80 rows x 23 columns]

In [2]:
# practice 2.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data


Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [3]:
# practice 2.3: import Sequential class and Dense class from keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
# practice 2.4: build a three-layer neural network with binary function as output
model = Sequential()
model.add()

TypeError: ignored

In [ ]:
## Practice 3.1: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [ ]:
## Practice 3.2: Define the first hidden layer in model architecture
from keras.models import Sequential
from keras.layers import Dense
model = Sequential() # initialize Sequential model

# add connection layers into sequential model
model.add(Dense(100, input_shape=(22,),activation='relu')) # input layer -> hidden layer 1

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               2300      
                                                                 
Total params: 2,300
Trainable params: 2,300
Non-trainable params: 0
_________________________________________________________________


In [ ]:
## Practice 4: Add more hidden layers and output layers into network
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 100)               2300      
                                                                 
 dense_2 (Dense)             (None, 100)               10100     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
## Practice 5.1: Compile the model for backpropagation, and start training model on data
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer

# Compile model, use binary crossentropy, and stochastic gradient descent for optimization
model.compile(loss='binary_crossentropy', optimizer='SGD', metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 100)               2300      
                                                                 
 dense_5 (Dense)             (None, 100)               10100     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10 
model.fit(train_features, train_label, epochs = 10)

Epoch 1/10
3/3 [==============================] - 6s 12ms/step - loss: 0.6834 - accuracy: 0.5625
Epoch 2/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6817 - accuracy: 0.6250
Epoch 3/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6801 - accuracy: 0.6250
Epoch 4/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6782 - accuracy: 0.6375
Epoch 5/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6764 - accuracy: 0.6375
Epoch 6/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6746 - accuracy: 0.6250
Epoch 7/10
3/3 [==============================] - 0s 7ms/step - loss: 0.6728 - accuracy: 0.6375
Epoch 8/10
3/3 [==============================] - 0s 7ms/step - loss: 0.6710 - accuracy: 0.6375
Epoch 9/10
3/3 [==============================] - 0s 9ms/step - loss: 0.6694 - accuracy: 0.6375
Epoch 10/10
3/3 [==============================] - 0s 8ms/step - loss: 0.6675 - accuracy: 0.6375


In [ ]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10 
model.fit(train_features, train_label, epochs = 100)

Epoch 1/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6657 - accuracy: 0.6375
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6641 - accuracy: 0.6250
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6625 - accuracy: 0.6250
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6611 - accuracy: 0.6375
Epoch 5/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6596 - accuracy: 0.6500
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6579 - accuracy: 0.6500
Epoch 7/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6565 - accuracy: 0.6500
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6552 - accuracy: 0.6250
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6535 - accuracy: 0.6500
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6522 - accuracy: 0.6500
Epoch 11/100
3/3 [===========

In [ ]:
## practice 6.1: save the model to local disk, or load the model for predictions
from tensorflow.keras.models import load_model
model.save("SPECT_model.h5")
model_loaded = load_model("SPECT_model.h5")

In [ ]:
## practice 6.2: evaluate the model performance using evaluate() method
model_loaded.evaluate(train_features, train_label)

3/3 [==============================] - 0s 5ms/step - loss: 0.5578 - accuracy: 0.7625


[0.5577572584152222, 0.762499988079071]

In [ ]:
## practice 6.3: make a prediction on training set and test set
train_predictions = model_loaded.predict(train_features)
test_predictions = model_loaded.predict(test_features)
print("train_predictions: ",train_predictions) # the prediction is the probability of the class

6/6 [==============================] - 0s 3ms/step
train_predictions:  [[0.50736916]
 [0.7275282 ]
 [0.67782456]
 [0.58105564]
 [0.51731884]
 [0.49791333]
 [0.83238685]
 [0.5242005 ]
 [0.7414483 ]
 [0.5733674 ]
 [0.72585946]
 [0.39196968]
 [0.39196968]
 [0.39196968]
 [0.5359096 ]
 [0.43270978]
 [0.838995  ]
 [0.43154344]
 [0.39196968]
 [0.58623487]
 [0.44039747]
 [0.49791333]
 [0.47121462]
 [0.39196968]
 [0.58533007]
 [0.39950275]
 [0.58975905]
 [0.6436752 ]
 [0.5405905 ]
 [0.635286  ]
 [0.8197255 ]
 [0.39196968]
 [0.6066309 ]
 [0.7387077 ]
 [0.49152735]
 [0.5293776 ]
 [0.4968776 ]
 [0.39950275]
 [0.51423883]
 [0.39196968]
 [0.6749203 ]
 [0.7584103 ]
 [0.6327049 ]
 [0.4725166 ]
 [0.57312435]
 [0.61482346]
 [0.49112526]
 [0.6855297 ]
 [0.5404407 ]
 [0.63752115]
 [0.7258173 ]
 [0.7387733 ]
 [0.39196968]
 [0.5977638 ]
 [0.6295609 ]
 [0.679812  ]
 [0.8321518 ]
 [0.49791333]
 [0.39196968]
 [0.39196968]
 [0.49791333]
 [0.6312941 ]
 [0.8745784 ]
 [0.727644  ]
 [0.66424876]
 [0.5462949 ]
 [0.3

In [ ]:
## practice 6.4: convert probability to labels
import numpy as np
train_prediction_labels = (train_predictions > 0.5).astype(int)
test_prediction_labels = (test_predictions > 0.5).astype(int)

In [ ]:
## practice 6.5: convert probability to labels
from sklearn.metrics import accuracy_score
print("Training accuracy: ", accuracy_score(train_label, train_prediction_labels))
print("Test accuracy: ", accuracy_score(test_label, test_prediction_labels))

Training accuracy:  0.7625
Test accuracy:  0.839572192513369


In [ ]:
from sklearn.metrics import precision_score, f1_score, recall_score

# Precision
train_precision = precision_score(train_label, train_prediction_labels, average='weighted')
test_precision = precision_score(test_label, test_prediction_labels, average='weighted')

# F1 score
train_f1 = f1_score(train_label, train_prediction_labels, average='weighted')
test_f1 = f1_score(test_label, test_prediction_labels, average='weighted')

# Recall
train_recall = recall_score(train_label, train_prediction_labels, average='weighted')
test_recall = recall_score(test_label, test_prediction_labels, average='weighted')


print("Training precision: ", train_precision)
print("Test precision: ", test_precision)

print("Training F1 score: ", train_f1)
print("Test F1 score: ", test_f1)

print("Training recall: ", train_recall)
print("Test recall: ", test_recall)

Training precision:  0.7764976958525345
Test precision:  0.8992140054758652
Training F1 score:  0.7594556100648836
Test F1 score:  0.8635598074185811
Training recall:  0.7625
Test recall:  0.839572192513369


In [ ]:
# practice 7.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
66      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
12      1   1   0   0   0   1   0   0   0   0  ...    1    0    0    0    0   
23      1   0   0   0   0   0   0   0   1   0  ...    1    0    0    0    0   
52      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
53      0   0   0   1   0   0   0   0   0   0  ...    1    0    0    0    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
1       1   0   0   1   1   0   0   0   1   1  ...    1    1    0    0    0   
19      1   1   0   0   0   1   0   0   0   0  ...    1    0    0    0    0   
31      1   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
11      1   1   1   0   0   1   1   1   0   1  ...    0    1    0    0    1   
79      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   

    F18  F19  F20  F21  F22  
66    0    0    0    0    1  
12    0    0    0    1    1  
23    0    0    0    0    0  
52    0    0    0    0    0  
53    0    0    0    0    0  
..  ...  ...  ...  ...  ...  
1     0    0    0    0    1  
19    0    0    1    0    0  
31    0    0    0    0    0  
11    0    1    1    0    0  
79    0    0    0    0    0  

[80 rows x 23 columns]

In [ ]:
# practice 7.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [ ]:
## Practice 7.3: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [ ]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(100, 100), activation='relu', solver='sgd', 
                      batch_size='auto', learning_rate='constant', learning_rate_init=0.001, 
                      max_iter=200, shuffle=True, random_state=42)

model.fit(train_features, train_label) # train the model on the training data

# Use the trained model to predict on the testing data
y_pred = model.predict(test_features)

accuracy = accuracy_score(test_label, y_pred)
print('Accuracy:', accuracy)

f1score = f1_score(test_label, y_pred)
print('F1 score:', f1score)

Accuracy: 0.7967914438502673
F1 score: 0.880503144654088


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
!pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Practice 8.1: Monitor the model performance using validation set
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.2, random_state=42)

validation_data = (X_val, y_val)
## option 1: monitor the model training using validation data
model_loaded.fit(X_train, y_train, validation_data= validation_data, epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 393ms/step - loss: 0.5664 - accuracy: 0.7500 - val_loss: 0.5229 - val_accuracy: 0.8125
Epoch 2/20
2/2 [==============================] - 0s 59ms/step - loss: 0.5657 - accuracy: 0.7500 - val_loss: 0.5228 - val_accuracy: 0.8125
Epoch 3/20
2/2 [==============================] - 0s 28ms/step - loss: 0.5650 - accuracy: 0.7500 - val_loss: 0.5226 - val_accuracy: 0.8125
Epoch 4/20
2/2 [==============================] - 0s 45ms/step - loss: 0.5644 - accuracy: 0.7500 - val_loss: 0.5225 - val_accuracy: 0.8125
Epoch 5/20
2/2 [==============================] - 0s 55ms/step - loss: 0.5637 - accuracy: 0.7500 - val_loss: 0.5224 - val_accuracy: 0.8125
Epoch 6/20
2/2 [==============================] - 0s 28ms/step - loss: 0.5631 - accuracy: 0.7500 - val_loss: 0.5222 - val_accuracy: 0.8125
Epoch 7/20
2/2 [==============================] - 0s 28ms/step - loss: 0.5623 - accuracy: 0.7500 - val_loss: 0.5221 - val_accuracy: 0.8125
Epoch 8/20
2/2 [==========

In [ ]:
## option 2: monitor the model training using validation data
model_loaded.fit(X_train, y_train, validation_split=0.2, epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 253ms/step - loss: 0.5596 - accuracy: 0.7451 - val_loss: 0.5278 - val_accuracy: 0.8462
Epoch 2/20
2/2 [==============================] - 0s 122ms/step - loss: 0.5587 - accuracy: 0.7451 - val_loss: 0.5283 - val_accuracy: 0.8462
Epoch 3/20
2/2 [==============================] - 0s 73ms/step - loss: 0.5577 - accuracy: 0.7451 - val_loss: 0.5288 - val_accuracy: 0.8462
Epoch 4/20
2/2 [==============================] - 0s 74ms/step - loss: 0.5570 - accuracy: 0.7451 - val_loss: 0.5295 - val_accuracy: 0.8462
Epoch 5/20
2/2 [==============================] - 0s 71ms/step - loss: 0.5558 - accuracy: 0.7647 - val_loss: 0.5297 - val_accuracy: 0.8462
Epoch 6/20
2/2 [==============================] - 0s 78ms/step - loss: 0.5549 - accuracy: 0.7647 - val_loss: 0.5301 - val_accuracy: 0.8462
Epoch 7/20
2/2 [==============================] - 0s 77ms/step - loss: 0.5540 - accuracy: 0.7647 - val_loss: 0.5302 - val_accuracy: 0.8462
Epoch 8/20
2/2 [=========

In [ ]:
#Step 9a

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split

def build_model():
  model = Sequential()
  model.add(Dense(100, activation = "relu"))
  model.add(Dense(100, activation = "relu"))
  model.add(Dense(1, activation = "sigmoid"))
  return model

X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size = 0.3, random_state = 42)
learning_rate_options = [.001, .01, .1]

for learning_rate in learning_rate_options:
  model = build_model()
  optimizer_to_run = SGD(lr = learning_rate)
  model.compile(loss = "binary_crossentropy", optimizer = optimizer_to_run, metrics = ["accuracy"] )
  model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs = 100, verbose = None)
  model.save("model_lr" + str(learning_rate) + ".h5")
  print("learning rate: ", learning_rate, " Validation Accuracy: ", model.evaluate(X_val, y_val, verbose = None))

/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.001  Validation Accuracy:  [0.6933940052986145, 0.5]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.01  Validation Accuracy:  [0.6650376915931702, 0.6666666865348816]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.1  Validation Accuracy:  [0.8238123059272766, 0.6666666865348816]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split

def build_model(n_layers = 2):
  model = Sequential()
  for i in range(n_layers):
    model.add(Dense(100, activation = "relu"))
  model.add(Dense(1, activation = "sigmoid"))
  return model

X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size = 0.3, random_state = 42)
layers = [1,2,3,4,5]

for n_layer in layers:
  model = build_model(n_layer)
  optimizer_to_run = SGD(lr = .1)
  model.compile(loss = "binary_crossentropy", optimizer = optimizer_to_run, metrics = ["accuracy"])
  model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs = 100, verbose = None)
  model.save("model lr" + str(learning_rate)+ ".h5")
  print("Layers: ", n_layer, " Validation Accuracy: ", model.evaluate(X_val, y_val, verbose = None))


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  1  Validation Accuracy:  [0.6956262588500977, 0.6666666865348816]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  2  Validation Accuracy:  [0.8866307139396667, 0.625]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  3  Validation Accuracy:  [0.8468310236930847, 0.625]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  4  Validation Accuracy:  [1.0694743394851685, 0.5833333134651184]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  5  Validation Accuracy:  [1.2314692735671997, 0.625]


In [ ]:
# practice 9.1: setup iris dataset for multi-class classification
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

# get features from iris data
X = iris["data"][:, :] # using all features

# get binary labels for binary classification
y = iris["target"]

print(X.shape)
print(y)

(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
# practice 9.2: Define the neural network classifier with softmax function as output
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(10, input_shape=(X.shape[1],), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(5, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(3, activation='softmax')) # hidden layer 2 -> output layer (3 classes, use softmax function to calculate probability)

In [ ]:
# Compile model, use categorical_crossentropy as loss function for softmax function
model.compile(loss='categorical_crossentropy',
optimizer='SGD',
metrics=['accuracy'])

In [ ]:
# practice 9.3: Train the model on the training set
from keras.utils import to_categorical

# Convert target labels to one-hot encoded format
y_encoded = to_categorical(y)

# Train the model
model.fit(X, y_encoded, validation_split=0.2, epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 67ms/step - loss: 1.4818 - accuracy: 0.4167 - val_loss: 3.1497 - val_accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 14ms/step - loss: 1.3795 - accuracy: 0.4167 - val_loss: 2.5197 - val_accuracy: 0.0000e+00
Epoch 3/10
4/4 [==============================] - 0s 12ms/step - loss: 1.2912 - accuracy: 0.4167 - val_loss: 2.0121 - val_accuracy: 0.0000e+00
Epoch 4/10
4/4 [==============================] - 0s 12ms/step - loss: 1.2050 - accuracy: 0.4167 - val_loss: 1.8979 - val_accuracy: 0.0000e+00
Epoch 5/10
4/4 [==============================] - 0s 12ms/step - loss: 1.1457 - accuracy: 0.4167 - val_loss: 1.7476 - val_accuracy: 0.0000e+00
Epoch 6/10
4/4 [==============================] - 0s 13ms/step - loss: 1.0995 - accuracy: 0.4167 - val_loss: 1.5553 - val_accuracy: 0.0000e+00
Epoch 7/10
4/4 [==============================] - 0s 12ms/step - loss: 1.0548 - accuracy: 0.4167 - val_loss: 1.3827 - val_accuracy: 0.0000e+00

In [ ]:
## re-fit model on the training features and one-hot encoding labels
import tensorflow as tf
y_onehot = tf.keras.utils.to_categorical(y, num_classes=3, dtype='float32')
print(y_onehot)
model.fit(X, y_onehot, validation_split = 0.2, epochs=10)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [ ]:

train_loss, train_acc = model.evaluate(X, y_onehot)


print('Train loss:', train_loss)
print('Train accuracy:', train_acc)

5/5 [==============================] - 0s 4ms/step - loss: 0.9134 - accuracy: 0.6667
Test loss: 0.913425087928772
Test accuracy: 0.6666666865348816
