In [1]:
# practice 2.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
40      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
27      1   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
14      1   1   0   1   1   0   0   1   1   1  ...    1    1    1    1    0   
1       1   0   0   1   1   0   0   0   1   1  ...    1    1    0    0    0   
18      1   1   0   1   0   1   0   1   1   0  ...    1    0    0    0    1   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
77      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   
54      0   1   0   0   0   1   0   1   0   0  ...    0    0    0    0    0   
11      1   1   1   0   0   1   1   1   0   1  ...    0    1    0    0    1   
21      1   1   0   0   0   1   1   0   1   0  ...    0    0    0    0    0   
68      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   

    F18  F19  F20  F21  F22  
40    0    0    0    0    1  
27    0    0    1    0    0  
14    1    1    0    1    1  
1     0    0    0    0    1  
18    0    0    1    1    0  
..  ...  ...  ...  ...  ...  
77    0    1    0    0    0  
54    0    0    0    0    1  
11    0    1    1    0    0  
21    0    1    1    0    0  
68    0    0    0    0    0  

[80 rows x 23 columns]

In [2]:
# practice 2.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data


Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [3]:
# practice 2.3: import Sequential class and Dense class from keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
## Practice 3.1: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [5]:
## Practice 3.2: Define the first hidden layer in model architecture
from keras.models import Sequential
from keras.layers import Dense
model = Sequential() # initialize Sequential model

# add connection layers into sequential model
model.add(Dense(100, input_shape=(22,),activation='relu')) # input layer -> hidden layer 1

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               2300      
                                                                 
Total params: 2,300
Trainable params: 2,300
Non-trainable params: 0
_________________________________________________________________


In [6]:
## Practice 4: Add more hidden layers and output layers into network
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 100)               2300      
                                                                 
 dense_2 (Dense)             (None, 100)               10100     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [7]:
## Practice 5.1: Compile the model for backpropagation, and start training model on data
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer

# Compile model, use binary crossentropy, and stochastic gradient descent for optimization
model.compile(loss='binary_crossentropy', optimizer='SGD', metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 100)               2300      
                                                                 
 dense_5 (Dense)             (None, 100)               10100     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [8]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10
model.fit(train_features, train_label, epochs = 10)

Epoch 1/10
3/3 [==============================] - 5s 8ms/step - loss: 0.7161 - accuracy: 0.4750
Epoch 2/10
3/3 [==============================] - 0s 5ms/step - loss: 0.7120 - accuracy: 0.4875
Epoch 3/10
3/3 [==============================] - 0s 5ms/step - loss: 0.7077 - accuracy: 0.4250
Epoch 4/10
3/3 [==============================] - 0s 5ms/step - loss: 0.7036 - accuracy: 0.4250
Epoch 5/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6994 - accuracy: 0.4875
Epoch 6/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6959 - accuracy: 0.4875
Epoch 7/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6928 - accuracy: 0.4750
Epoch 8/10
3/3 [==============================] - 0s 7ms/step - loss: 0.6897 - accuracy: 0.5125
Epoch 9/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6867 - accuracy: 0.5375
Epoch 10/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6838 - accuracy: 0.5500


In [9]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10
model.fit(train_features, train_label, epochs = 100)

Epoch 1/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6809 - accuracy: 0.5625
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6781 - accuracy: 0.5750
Epoch 3/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6754 - accuracy: 0.5625
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6730 - accuracy: 0.5750
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6705 - accuracy: 0.5625
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6683 - accuracy: 0.6750
Epoch 7/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6662 - accuracy: 0.6750
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6644 - accuracy: 0.6875
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6624 - accuracy: 0.6750
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6602 - accuracy: 0.6625
Epoch 11/100
3/3 [===========

In [10]:
## practice 6.1: save the model to local disk, or load the model for predictions
from tensorflow.keras.models import load_model
model.save("SPECT_model.h5")
model_loaded = load_model("SPECT_model.h5")

In [11]:
## practice 6.2: evaluate the model performance using evaluate() method
model_loaded.evaluate(train_features, train_label)

3/3 [==============================] - 0s 5ms/step - loss: 0.5461 - accuracy: 0.7875


[0.5461469888687134, 0.7875000238418579]

In [12]:
## practice 6.3: make a prediction on training set and test set
train_predictions = model_loaded.predict(train_features)
test_predictions = model_loaded.predict(test_features)
print("train_predictions: ",train_predictions) # the prediction is the probability of the class

6/6 [==============================] - 0s 2ms/step
train_predictions:  [[0.48285738]
 [0.45634001]
 [0.8389568 ]
 [0.67135227]
 [0.7571973 ]
 [0.41242245]
 [0.6956503 ]
 [0.48285738]
 [0.44520077]
 [0.41242245]
 [0.41464105]
 [0.5566774 ]
 [0.7231978 ]
 [0.867242  ]
 [0.6470072 ]
 [0.53328323]
 [0.41242245]
 [0.7502398 ]
 [0.48285738]
 [0.85748935]
 [0.674921  ]
 [0.56059283]
 [0.6800792 ]
 [0.41242245]
 [0.84929866]
 [0.6041652 ]
 [0.41242245]
 [0.45869628]
 [0.5203707 ]
 [0.5783338 ]
 [0.5368212 ]
 [0.724459  ]
 [0.68239754]
 [0.41242245]
 [0.48285738]
 [0.58519566]
 [0.681436  ]
 [0.45634001]
 [0.53337777]
 [0.47439176]
 [0.51380527]
 [0.41242245]
 [0.86033636]
 [0.41242245]
 [0.53296614]
 [0.6933822 ]
 [0.41242245]
 [0.76534367]
 [0.4772248 ]
 [0.57036453]
 [0.48756105]
 [0.4909061 ]
 [0.48818013]
 [0.7088775 ]
 [0.41242245]
 [0.6610522 ]
 [0.6269275 ]
 [0.655545  ]
 [0.59133476]
 [0.41242245]
 [0.46962363]
 [0.47988924]
 [0.5766093 ]
 [0.63891774]
 [0.63094866]
 [0.41242245]
 [0.5

In [13]:
## practice 6.4: convert probability to labels
import numpy as np
train_prediction_labels = (train_predictions > 0.5).astype(int)
test_prediction_labels = (test_predictions > 0.5).astype(int)

In [14]:
## practice 6.5: convert probability to labels
from sklearn.metrics import accuracy_score
print("Training accuracy: ", accuracy_score(train_label, train_prediction_labels))
print("Test accuracy: ", accuracy_score(test_label, test_prediction_labels))

Training accuracy:  0.7875
Test accuracy:  0.8502673796791443


In [15]:
from sklearn.metrics import precision_score, f1_score, recall_score

# Precision
train_precision = precision_score(train_label, train_prediction_labels, average='weighted')
test_precision = precision_score(test_label, test_prediction_labels, average='weighted')

# F1 score
train_f1 = f1_score(train_label, train_prediction_labels, average='weighted')
test_f1 = f1_score(test_label, test_prediction_labels, average='weighted')

# Recall
train_recall = recall_score(train_label, train_prediction_labels, average='weighted')
test_recall = recall_score(test_label, test_prediction_labels, average='weighted')


print("Training precision: ", train_precision)
print("Test precision: ", test_precision)

print("Training F1 score: ", train_f1)
print("Test F1 score: ", test_f1)

print("Training recall: ", train_recall)
print("Test recall: ", test_recall)

Training precision:  0.7965828497743391
Test precision:  0.9076976154775016
Training F1 score:  0.7858604944103289
Test F1 score:  0.8726558202573423
Training recall:  0.7875
Test recall:  0.8502673796791443


In [16]:
# practice 7.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
54      0   1   0   0   0   1   0   1   0   0  ...    0    0    0    0    0   
3       1   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
8       1   0   0   1   0   0   0   1   1   0  ...    1    0    1    0    0   
51      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
37      1   1   0   0   1   0   0   0   0   0  ...    0    0    0    0    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
66      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
58      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
9       1   0   1   0   0   0   0   1   1   0  ...    0    0    0    0    0   
44      0   0   1   0   0   0   0   1   0   0  ...    0    0    0    0    0   
34      1   1   0   1   1   1   0   0   1   1  ...    1    1    1    0    0   

    F18  F19  F20  F21  F22  
54    0    0    0    0    1  
3     0    0    1    1    1  
8     0    0    0    1    1  
51    0    0    0    0    0  
37    0    0    0    0    0  
..  ...  ...  ...  ...  ...  
66    0    0    0    0    1  
58    0    0    0    0    0  
9     0    0    0    0    0  
44    0    0    0    1    0  
34    0    0    0    1    0  

[80 rows x 23 columns]

In [17]:
# practice 7.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [18]:
## Practice 7.3: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [19]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(100, 100), activation='relu', solver='sgd',
                      batch_size='auto', learning_rate='constant', learning_rate_init=0.001,
                      max_iter=200, shuffle=True, random_state=42)

model.fit(train_features, train_label) # train the model on the training data

# Use the trained model to predict on the testing data
y_pred = model.predict(test_features)

accuracy = accuracy_score(test_label, y_pred)
print('Accuracy:', accuracy)

f1score = f1_score(test_label, y_pred)
print('F1 score:', f1score)

Accuracy: 0.7967914438502673
F1 score: 0.880503144654088


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
!pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [21]:
# Practice 8.1: Monitor the model performance using validation set
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.2, random_state=42)

validation_data = (X_val, y_val)
## option 1: monitor the model training using validation data
model_loaded.fit(X_train, y_train, validation_data= validation_data, epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 73ms/step - loss: 0.5330 - accuracy: 0.8125 - val_loss: 0.5984 - val_accuracy: 0.6875
Epoch 2/20
2/2 [==============================] - 0s 28ms/step - loss: 0.5321 - accuracy: 0.8125 - val_loss: 0.5986 - val_accuracy: 0.6875
Epoch 3/20
2/2 [==============================] - 0s 28ms/step - loss: 0.5310 - accuracy: 0.8125 - val_loss: 0.5987 - val_accuracy: 0.6875
Epoch 4/20
2/2 [==============================] - 0s 81ms/step - loss: 0.5301 - accuracy: 0.8125 - val_loss: 0.5988 - val_accuracy: 0.6875
Epoch 5/20
2/2 [==============================] - 0s 73ms/step - loss: 0.5291 - accuracy: 0.8125 - val_loss: 0.5989 - val_accuracy: 0.6875
Epoch 6/20
2/2 [==============================] - 0s 61ms/step - loss: 0.5286 - accuracy: 0.8125 - val_loss: 0.5990 - val_accuracy: 0.6875
Epoch 7/20
2/2 [==============================] - 0s 42ms/step - loss: 0.5272 - accuracy: 0.8125 - val_loss: 0.5991 - val_accuracy: 0.6875
Epoch 8/20
2/2 [===========

In [22]:
## option 2: monitor the model training using validation data
model_loaded.fit(X_train, y_train, validation_split=0.2, epochs = 20)

Epoch 1/20
2/2 [==============================] - 0s 109ms/step - loss: 0.5086 - accuracy: 0.8235 - val_loss: 0.5357 - val_accuracy: 0.7692
Epoch 2/20
2/2 [==============================] - 0s 65ms/step - loss: 0.5078 - accuracy: 0.8235 - val_loss: 0.5351 - val_accuracy: 0.7692
Epoch 3/20
2/2 [==============================] - 0s 52ms/step - loss: 0.5064 - accuracy: 0.8235 - val_loss: 0.5351 - val_accuracy: 0.7692
Epoch 4/20
2/2 [==============================] - 0s 52ms/step - loss: 0.5053 - accuracy: 0.8235 - val_loss: 0.5351 - val_accuracy: 0.7692
Epoch 5/20
2/2 [==============================] - 0s 60ms/step - loss: 0.5041 - accuracy: 0.8235 - val_loss: 0.5350 - val_accuracy: 0.7692
Epoch 6/20
2/2 [==============================] - 0s 58ms/step - loss: 0.5029 - accuracy: 0.8235 - val_loss: 0.5347 - val_accuracy: 0.7692
Epoch 7/20
2/2 [==============================] - 0s 42ms/step - loss: 0.5018 - accuracy: 0.8235 - val_loss: 0.5343 - val_accuracy: 0.7692
Epoch 8/20
2/2 [==========

In [23]:
#Step 9a

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split

def build_model():
  model = Sequential()
  model.add(Dense(100, activation = "relu"))
  model.add(Dense(100, activation = "relu"))
  model.add(Dense(1, activation = "sigmoid"))
  return model

X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size = 0.3, random_state = 42)
learning_rate_options = [.001, .01, .1]

for learning_rate in learning_rate_options:
  model = build_model()
  optimizer_to_run = SGD(lr = learning_rate)
  model.compile(loss = "binary_crossentropy", optimizer = optimizer_to_run, metrics = ["accuracy"] )
  model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs = 100, verbose = None)
  model.save("model_lr" + str(learning_rate) + ".h5")
  print("learning rate: ", learning_rate, " Validation Accuracy: ", model.evaluate(X_val, y_val, verbose = None))

/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.001  Validation Accuracy:  [0.7032627463340759, 0.4583333432674408]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.01  Validation Accuracy:  [0.6465501189231873, 0.6666666865348816]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


learning rate:  0.1  Validation Accuracy:  [0.8990432620048523, 0.7083333134651184]


In [24]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split

def build_model(n_layers = 2):
  model = Sequential()
  for i in range(n_layers):
    model.add(Dense(100, activation = "relu"))
  model.add(Dense(1, activation = "sigmoid"))
  return model

X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size = 0.3, random_state = 42)
layers = [1,2,3,4,5]

for n_layer in layers:
  model = build_model(n_layer)
  optimizer_to_run = SGD(lr = .1)
  model.compile(loss = "binary_crossentropy", optimizer = optimizer_to_run, metrics = ["accuracy"])
  model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs = 100, verbose = None)
  model.save("model lr" + str(learning_rate)+ ".h5")
  print("Layers: ", n_layer, " Validation Accuracy: ", model.evaluate(X_val, y_val, verbose = None))


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  1  Validation Accuracy:  [0.7347304821014404, 0.7083333134651184]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  2  Validation Accuracy:  [0.8815460205078125, 0.6666666865348816]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  3  Validation Accuracy:  [1.0029157400131226, 0.7083333134651184]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  4  Validation Accuracy:  [1.2909539937973022, 0.625]


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  5  Validation Accuracy:  [1.1069591045379639, 0.7083333134651184]


In [25]:
# practice 9.1: setup iris dataset for multi-class classification
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

# get features from iris data
X = iris["data"][:, :] # using all features

# get binary labels for binary classification
y = iris["target"]

print(X.shape)
print(y)

(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [26]:
# practice 9.2: Define the neural network classifier with softmax function as output
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(10, input_shape=(X.shape[1],), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(5, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(3, activation='softmax')) # hidden layer 2 -> output layer (3 classes, use softmax function to calculate probability)

In [27]:
# Compile model, use categorical_crossentropy as loss function for softmax function
model.compile(loss='categorical_crossentropy',
optimizer='SGD',
metrics=['accuracy'])

In [28]:
# practice 9.3: Train the model on the training set
from keras.utils import to_categorical

# Convert target labels to one-hot encoded format
y_encoded = to_categorical(y)

# Train the model
model.fit(X, y_encoded, validation_split=0.2, epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 64ms/step - loss: 1.2071 - accuracy: 0.4167 - val_loss: 1.4359 - val_accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 12ms/step - loss: 1.0280 - accuracy: 0.4167 - val_loss: 1.1980 - val_accuracy: 0.0000e+00
Epoch 3/10
4/4 [==============================] - 0s 12ms/step - loss: 0.9863 - accuracy: 0.4500 - val_loss: 1.1249 - val_accuracy: 0.0000e+00
Epoch 4/10
4/4 [==============================] - 0s 12ms/step - loss: 0.9673 - accuracy: 0.4667 - val_loss: 1.1355 - val_accuracy: 0.0000e+00
Epoch 5/10
4/4 [==============================] - 0s 11ms/step - loss: 0.9532 - accuracy: 0.4667 - val_loss: 1.1251 - val_accuracy: 0.0000e+00
Epoch 6/10
4/4 [==============================] - 0s 12ms/step - loss: 0.9407 - accuracy: 0.4750 - val_loss: 1.1301 - val_accuracy: 0.0000e+00
Epoch 7/10
4/4 [==============================] - 0s 17ms/step - loss: 0.9294 - accuracy: 0.4667 - val_loss: 1.1292 - val_accuracy: 0.0000e+00

In [29]:
## re-fit model on the training features and one-hot encoding labels
import tensorflow as tf
y_onehot = tf.keras.utils.to_categorical(y, num_classes=3, dtype='float32')
print(y_onehot)
model.fit(X, y_onehot, validation_split = 0.2, epochs=10)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [30]:

train_loss, train_acc = model.evaluate(X, y_onehot)


print('Train loss:', train_loss)
print('Train accuracy:', train_acc)

5/5 [==============================] - 0s 7ms/step - loss: 0.8697 - accuracy: 0.5867
Train loss: 0.8697150945663452
Train accuracy: 0.5866666436195374
